UMHackerPhone = [];

UMHackerPhone.CloseKey = "Escape"

UMHackerPhone.BlackoutSeconds = 10

UMHackerPhone.Cams = {
    [1]  : "Pacific Bank CAM#1",
    [2]  : "Pacific Bank CAM#2",
    [3]  : "Pacific Bank CAM#3",
    [4]  : "Limited Ltd Grove St. CAM#1",
    [5]  : "Rob's Liqour Prosperity St. CAM#1",
    [6]  : "Rob's Liqour San Andreas Ave. CAM#1",
    [7]  : "Limited Ltd Ginger St. CAM#1",
    [8]  : "24/7 Supermarkt Innocence Blvd. CAM#1",
    [9]  : "Rob's Liqour El Rancho Blvd. CAM#1",
    [10] : "Limited Ltd West Mirror Drive CAM#1",
    [11] : "24/7 Supermarkt Clinton Ave CAM#1",
    [12] : "Limited Ltd Banham Canyon Dr CAM#1",
    [13] : "Rob's Liqour Great Ocean Hwy CAM#1",
    [14] : "24/7 Supermarkt Ineseno Road CAM#1",
    [15] : "24/7 Supermarkt Barbareno Rd. CAM#1",
    [16] : "24/7 Supermarkt Route 68 CAM#1",
    [17] : "Rob's Liqour Route 68 CAM#1",
    [18] : "24/7 Supermarkt Senora Fwy CAM#1",
    [19] : "24/7 Supermarkt Alhambra Dr. CAM#1",
    [20] : "24/7 Supermarkt Senora Fwy CAM#2",
    [21] : "Fleeca Bank Hawick Ave CAM#1",
    [22] : "Fleeca Bank Legion Square CAM#1",
    [23] : "Fleeca Bank Hawick Ave CAM#2",
    [24] : "Fleeca Bank Del Perro Blvd CAM#1",
    [25] : "Fleeca Bank Great Ocean Hwy CAM#1",
    [26] : "Paleto Bank CAM#1",
    [27] : "Del Vecchio Liquor Paleto Bay",
    [28] : "Don's Country Store Paleto Bay CAM#1",
    [29] : "Don's Country Store Paleto Bay CAM#2",
    [30] : "Don's Country Store Paleto Bay CAM#3",
    [31] : "Vangelico Jewelery CAM#1",
    [32] : "Vangelico Jewelery CAM#2",
    [33] : "Vangelico Jewelery CAM#3",
    [34] : "Vangelico Jewelery CAM#4",
},

UMHackerPhone.Lang = {
    lastname: "Lastname:",
    firstname: "Firstname:",
    dob: "Birthday:",
    bankmoney: "Bank Money:",
    number: "P.Number:",
    blackout: "Blackout",
    userinfo: "User Information",
    vehicle: "Vehicle",
    vehicletrack: "Vehicle Tracking",
    blackout: "Blackout",
    plate: "Plate: ",
    model: "Model: ",
    engine: "Engine: ",
    securitycams: "Security Cams",
    botnet: "Terminal",
    refresh: "Refresh",
    delete: "Delete",
    disabletracker: "Disable Tracker",
    explosion: "Explosion",
    hackpower: "Hack power station",
    fixpower: "Fix power station Seconds: ",
}