CREATE TABLE IF NOT EXISTS `trackers` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`cid` VARCHAR(50) DEFAULT NULL,
	`vid` VARCHAR(50) DEFAULT NULL,
	`plate` VARCHAR(50) DEFAULT NULL,
	`model` VARCHAR(50) DEFAULT NULL,
	`engine` FLOAT DEFAULT '1000',
	`distance` FLOAT DEFAULT NULL,
	PRIMARY KEY (`id`),
	KEY `id` (`id`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;